# requiring the environment of NodeJS 10
image: node:10

# add 'node_modules' to cache for speeding up builds
cache:
  paths:
    - node_modules/ # Node modules and dependencies

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - npm install gitbook-cli -g
    - gitbook fetch 3.2.3
    - gitbook install
    - gitbook build . public # build to public path
  artifacts:
    paths:
      - public
    #expire_in: 1 week
  only:
    - master # this job will affect only the 'master' branch
